export const mockData = {
  'answers': {
    'Octane: How old are you?': '26-34',
    'Octane: Quiz result': 'Dynamic results page',
    'Octane: Type a free-form response': 'Valik',
    'Octane: What is your gender?': 'Non-Binary',
    'Octane: What is your question?': 'Answer 1',
    'klaviyo_email_sync_list_id': null,
    'klaviyo_sms_sync_list_id': null,
    'quiz results URL': 'https://www.bareperformancenutrition.com/pages/bpn-quiz#r=eC0boJ54LQOlBHUT',
  },
  'phone': '',
  'phone_consent': 'null',
  'product_blocks': [
    [
      {
        'description': '<p><span style="color: rgb(119, 119, 119);">Servings - 25</span><br>Our superior endurance formula created with high-quality carbohydrates and electrolytes to help fuel, hydrate, and improve your performance during training sessions. Each serving contains 20 grams of carbohydrates, 350mg of sodium and a full electrolyte profile. Consume 1-2 servings of G.1.M Sport, about 20-30 minutes prior to or during endurance workouts. </p>',
        'id': '4621102153808',
        'image': 'https://cdn.shopify.com/s/files/1/1103/4864/files/BPNG1M-LL-6_Render_2048x2048.jpg?v=1732562717',
        'link': 'https://www.bareperformancenutrition.com/products/g-1-m-sport',
        'metafields': [],
        'price': 39.99,
        'price_formatted': '$39.99',
        'product_block_id': '24ccf697a6eaaf5cb757d33fd2e41b8eb634c8a9',
        'tags': [
          'best seller',
          'Endurance',
          'Flavored',
          'G1Msport',
          'growaov-collection',
          'Hydration Support',
          'Mid-workout Fuel',
          'Powder',
          'Pre-training Nutrition',
          'Maintain Energy',
          'Hydrate',
          'Recover',
          'Supplement',
        ],
        'title': 'G.1.M Sport',
        'type': 'Supplements',
        'variants': [
          {
            'compare_at_price': null,
            'compare_at_price_formatted': null,
            'id': '32407897636944',
            'metafields': [],
            'price': 39.99,
            'price_formatted': '$39.99',
            'title': 'G.1.M Sport / Endurance + Electrolytes',
          },
          {
            'compare_at_price': null,
            'compare_at_price_formatted': null,
            'id': '32407897669712',
            'metafields': [],
            'price': 39.99,
            'price_formatted': '$39.99',
            'title': 'G.1.M Sport / Endurance + Electrolytes',
          },
          {
            'compare_at_price': null,
            'compare_at_price_formatted': null,
            'id': '42524029321388',
            'metafields': [],
            'price': 39.99,
            'price_formatted': '$39.99',
            'title': 'G.1.M Sport / Endurance + Electrolytes',
          },
          {
            'compare_at_price': null,
            'compare_at_price_formatted': null,
            'id': '43914834084012',
            'metafields': [],
            'price': 39.99,
            'price_formatted': '$39.99',
            'title': 'G.1.M Sport / Endurance + Electrolytes',
          },
        ],
      },
      {
        'description': '<p><span style="color: rgb(119, 119, 119);">Servings - 50</span><br>Our electrolyte formula contains sodium, potassium, chloride and magnesium in a ratio for maximum fluid regulation to optimize your performance, and maintain appropriate levels of hydration. This product is great to use during the day and around workouts to optimize your fluid regulation and prevent symptoms of dehydration.</p>',
        'id': '6978181726380',
        'image': 'https://cdn.shopify.com/s/files/1/1103/4864/files/BPNELT_MNG-1_CL_RENDER_2048x2048.jpg?v=1728264598',
        'link': 'https://www.bareperformancenutrition.com/products/electrolytes',
        'metafields': [],
        'price': 44.99,
        'price_formatted': '$44.99',
        'product_block_id': '24ccf697a6eaaf5cb757d33fd2e41b8eb634c8a9',
        'tags': [
          'best seller',
          'contains-varient',
          'electrolytes',
          'Endurance',
          'Flavored',
          'growaov-collection',
          'Hydration',
          'Hydration Support',
          'Powder',
          'Maintain Energy',
          'Recover',
          'Supplement',
        ],
        'title': 'Electrolytes / Hydration Drink Mix',
        'type': 'Supplements',
        'variants': [
          {
            'compare_at_price': null,
            'compare_at_price_formatted': null,
            'id': '40587242209452',
            'metafields': [],
            'price': 44.99,
            'price_formatted': '$44.99',
            'title': 'Electrolytes / Hydration Drink Mix',
          },
          {
            'compare_at_price': null,
            'compare_at_price_formatted': null,
            'id': '42247273676972',
            'metafields': [],
            'price': 44.99,
            'price_formatted': '$44.99',
            'title': 'Electrolytes / Hydration Drink Mix',
          },
          {
            'compare_at_price': null,
            'compare_at_price_formatted': null,
            'id': '42310892781740',
            'metafields': [],
            'price': 44.99,
            'price_formatted': '$44.99',
            'title': 'Electrolytes / Hydration Drink Mix',
          },
          {
            'compare_at_price': null,
            'compare_at_price_formatted': null,
            'id': '43862091169964',
            'metafields': [],
            'price': 44.99,
            'price_formatted': '$44.99',
            'title': 'Electrolytes / Hydration Drink Mix',
          },
        ],
      },
      {
        'description': '<p>The Go Gel is our whole-food approach to satisfying your training and race-day nutrition needs. Formulated with simple ingredients that are easy to consume and will provide your body with the nutrients it needs during endurance training.</p>',
        'id': '7695188721836',
        'image': 'https://cdn.shopify.com/s/files/1/1103/4864/files/GEL-BRYCAF-BOX-2_RENDER_2048x2048.jpg?v=1736274738',
        'link': 'https://www.bareperformancenutrition.com/products/go-gel',
        'metafields': [],
        'price': 29.99,
        'price_formatted': '$29.99',
        'product_block_id': '24ccf697a6eaaf5cb757d33fd2e41b8eb634c8a9',
        'tags': [
          'best seller',
          'Endurance',
          'Flavored',
          'Gel',
          'Mid-workout Fuel',
          'on_the_go',
          'Pre-training Nutrition',
          'Maintain Energy',
          'Hydrate',
          'Supplement',
        ],
        'title': 'Go Gel / Endurance Gel',
        'type': 'Supplements',
        'variants': [
          {
            'compare_at_price': null,
            'compare_at_price_formatted': null,
            'id': '42760735064236',
            'metafields': [],
            'price': 29.99,
            'price_formatted': '$29.99',
            'title': 'Go Gel / Endurance Gel',
          },
          {
            'compare_at_price': null,
            'compare_at_price_formatted': null,
            'id': '43072976552108',
            'metafields': [],
            'price': 29.99,
            'price_formatted': '$29.99',
            'title': 'Go Gel / Endurance Gel',
          },
          {
            'compare_at_price': null,
            'compare_at_price_formatted': null,
            'id': '43534608728236',
            'metafields': [],
            'price': 29.99,
            'price_formatted': '$29.99',
            'title': 'Go Gel / Endurance Gel',
          },
          {
            'compare_at_price': null,
            'compare_at_price_formatted': null,
            'id': '43823421194412',
            'metafields': [],
            'price': 29.99,
            'price_formatted': '$29.99',
            'title': 'Go Gel / Endurance Gel',
          },
        ],
      },
    ],
  ],
  'quiz_results_url': 'https://www.bareperformancenutrition.com/pages/bpn-quiz#r=rzBJK2I0Y0q2G7O2',
  'sections': [
    {
      'bottom_content': [
        {
          'content_id': '95c4d999ae3e98583746193516b9ad5a70206c5a',
          'content_type': 'text',
          'display_on': '',
          'text': 'Want to start over?',
          'text_type': 'title',
        },
        {
          'content_id': 'f90832b0e8ca54c57919a13fd76adac38d2104ce',
          'content_type': 'text',
          'display_on': '',
          'text': 'Click below to take the quiz again.',
          'text_type': 'caption_text',
        },
        {
          'alt_text': '',
          'content_id': '3bf054f446fd00e813ced1b3ef1a0ce3caff2233',
          'content_type': 'button',
          'display_on': '',
          'open_link_same_tab': false,
          'size': 'medium',
          'text': 'RE-TAKE QUIZ',
          'type': 'primary_text',
          'url': 'https://www.bareperformancenutrition.com/pages/supplements-quiz',
        },
      ],
      'id': '24ccf697a6eaaf5cb757d33fd2e41b8eb634c8a9',
      'name': '',
      'products': [
        {
          'description': '<p><span style="color: rgb(119, 119, 119);">Servings - 25</span><br>Our superior endurance formula created with high-quality carbohydrates and electrolytes to help fuel, hydrate, and improve your performance during training sessions. Each serving contains 20 grams of carbohydrates, 350mg of sodium and a full electrolyte profile. Consume 1-2 servings of G.1.M Sport, about 20-30 minutes prior to or during endurance workouts. </p>',
          'id': '4621102153808',
          'image': 'https://cdn.shopify.com/s/files/1/1103/4864/files/BPNG1M-LL-6_Render_2048x2048.jpg?v=1732562717',
          'link': 'https://www.bareperformancenutrition.com/products/g-1-m-sport',
          'metafields': [],
          'price': 39.99,
          'price_formatted': '$39.99',
          'product_block_id': '24ccf697a6eaaf5cb757d33fd2e41b8eb634c8a9',
          'tags': [
            'best seller',
            'Endurance',
            'Flavored',
            'G1Msport',
            'growaov-collection',
            'Hydration Support',
            'Mid-workout Fuel',
            'Powder',
            'Pre-training Nutrition',
            'quiz-maintain-energy',
            'quiz-hydrate',
            'Supplement',
          ],
          'title': 'G.1.M Sport',
          'type': 'Supplements',
          'variants': [
            {
              'compare_at_price': null,
              'compare_at_price_formatted': null,
              'id': '32407897636944',
              'metafields': [],
              'price': 39.99,
              'price_formatted': '$39.99',
              'title': 'G.1.M Sport / Endurance + Electrolytes',
            },
            {
              'compare_at_price': null,
              'compare_at_price_formatted': null,
              'id': '32407897669712',
              'metafields': [],
              'price': 39.99,
              'price_formatted': '$39.99',
              'title': 'G.1.M Sport / Endurance + Electrolytes',
            },
            {
              'compare_at_price': null,
              'compare_at_price_formatted': null,
              'id': '42524029321388',
              'metafields': [],
              'price': 39.99,
              'price_formatted': '$39.99',
              'title': 'G.1.M Sport / Endurance + Electrolytes',
            },
            {
              'compare_at_price': null,
              'compare_at_price_formatted': null,
              'id': '43914834084012',
              'metafields': [],
              'price': 39.99,
              'price_formatted': '$39.99',
              'title': 'G.1.M Sport / Endurance + Electrolytes',
            },
          ],
        },
        {
          'description': '<p><span style="color: rgb(119, 119, 119);">Servings - 50</span><br>Our electrolyte formula contains sodium, potassium, chloride and magnesium in a ratio for maximum fluid regulation to optimize your performance, and maintain appropriate levels of hydration. This product is great to use during the day and around workouts to optimize your fluid regulation and prevent symptoms of dehydration.</p>',
          'id': '6978181726380',
          'image': 'https://cdn.shopify.com/s/files/1/1103/4864/files/BPNELT_MNG-1_CL_RENDER_2048x2048.jpg?v=1728264598',
          'link': 'https://www.bareperformancenutrition.com/products/electrolytes',
          'metafields': [],
          'price': 44.99,
          'price_formatted': '$44.99',
          'product_block_id': '24ccf697a6eaaf5cb757d33fd2e41b8eb634c8a9',
          'tags': [
            'best seller',
            'contains-varient',
            'electrolytes',
            'Endurance',
            'Flavored',
            'growaov-collection',
            'Hydration',
            'Hydration Support',
            'Powder',
            'quiz-hydrate',
            'Supplement',
          ],
          'title': 'Electrolytes / Hydration Drink Mix',
          'type': 'Supplements',
          'variants': [
            {
              'compare_at_price': null,
              'compare_at_price_formatted': null,
              'id': '40587242209452',
              'metafields': [],
              'price': 44.99,
              'price_formatted': '$44.99',
              'title': 'Electrolytes / Hydration Drink Mix',
            },
            {
              'compare_at_price': null,
              'compare_at_price_formatted': null,
              'id': '42247273676972',
              'metafields': [],
              'price': 44.99,
              'price_formatted': '$44.99',
              'title': 'Electrolytes / Hydration Drink Mix',
            },
            {
              'compare_at_price': null,
              'compare_at_price_formatted': null,
              'id': '42310892781740',
              'metafields': [],
              'price': 44.99,
              'price_formatted': '$44.99',
              'title': 'Electrolytes / Hydration Drink Mix',
            },
            {
              'compare_at_price': null,
              'compare_at_price_formatted': null,
              'id': '43862091169964',
              'metafields': [],
              'price': 44.99,
              'price_formatted': '$44.99',
              'title': 'Electrolytes / Hydration Drink Mix',
            },
          ],
        },
        {
          'description': '<p>The Go Gel is our whole-food approach to satisfying your training and race-day nutrition needs. Formulated with simple ingredients that are easy to consume and will provide your body with the nutrients it needs during endurance training.</p>',
          'id': '7695188721836',
          'image': 'https://cdn.shopify.com/s/files/1/1103/4864/files/GEL-BRYCAF-BOX-2_RENDER_2048x2048.jpg?v=1736274738',
          'link': 'https://www.bareperformancenutrition.com/products/go-gel',
          'metafields': [],
          'price': 29.99,
          'price_formatted': '$29.99',
          'product_block_id': '24ccf697a6eaaf5cb757d33fd2e41b8eb634c8a9',
          'tags': [
            'best seller',
            'Endurance',
            'Flavored',
            'Gel',
            'Mid-workout Fuel',
            'on_the_go',
            'Pre-training Nutrition',
            'quiz-recover',
            'Supplement',
          ],
          'title': 'Go Gel / Endurance Gel',
          'type': 'Supplements',
          'variants': [
            {
              'compare_at_price': null,
              'compare_at_price_formatted': null,
              'id': '42760735064236',
              'metafields': [],
              'price': 29.99,
              'price_formatted': '$29.99',
              'title': 'Go Gel / Endurance Gel',
            },
            {
              'compare_at_price': null,
              'compare_at_price_formatted': null,
              'id': '43072976552108',
              'metafields': [],
              'price': 29.99,
              'price_formatted': '$29.99',
              'title': 'Go Gel / Endurance Gel',
            },
            {
              'compare_at_price': null,
              'compare_at_price_formatted': null,
              'id': '43534608728236',
              'metafields': [],
              'price': 29.99,
              'price_formatted': '$29.99',
              'title': 'Go Gel / Endurance Gel',
            },
            {
              'compare_at_price': null,
              'compare_at_price_formatted': null,
              'id': '43823421194412',
              'metafields': [],
              'price': 29.99,
              'price_formatted': '$29.99',
              'title': 'Go Gel / Endurance Gel',
            },
          ],
        },
      ],
      'top_content': [
        {
          'content_id': '705244949657a627229bef3b231c346eecee0147',
          'content_type': 'text',
          'display_on': '',
          'text': 'Improved Endurance, Hydration and Potential',
          'text_type': 'title',
        },
        {
          'content_id': 'ae536a43565b59930e2dacb445cba47672381fbf',
          'content_type': 'text',
          'display_on': '',
          'text': 'Below you will find products that have been formulated to improve your training experience and results.',
          'text_type': 'body_text',
        },
      ],
    },
  ],
  'user': '9bba98e5024cd43a04bd8b12a3f60810e3a00f794fc3d73f6e6dbae1dccc88420cba005471014243ed5620ac24f98abaf1af4d130f77c999248fb5eb',
  'quiz_wrapper_element': {
    '__mutation_summary_node_map_id__': 487,
  },
};

const EVENTS = {
  COMPLETED: 'octane.quiz.completed',
  QUESTION_LOADED: 'octane.quiz.questionLoaded',
};

export const onOctaneQuizCompleted = (cb) => {
  document.addEventListener(
    EVENTS.COMPLETED,
    cb,
  );
};

export const onOctaneQuizQuestionLoaded = (cb) => {
  document.addEventListener(
    EVENTS.QUESTION_LOADED,
    cb,
  );
};
